import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';
import { reconstruct, scopeInfo, assertOmittableInitializer } from '../tools/reconstruct_bridge_core.mjs';
import { ROOT, hash } from '../tools/patch_utils.mjs';
import * as compat from '../reconstructed/bridge-core/src/file-tool-input-compat.js';
import * as fileTools from '../reconstructed/bridge-core/src/file-tool-registry.js';
import { IDE_TOOL_DEFINITIONS, IDE_TOOL_NAMES, BRIDGE_EXCLUDED_TOOL_NAMES } from '../reconstructed/bridge-core/src/ide-tool-definitions.js';
import { validateToolInput } from '../reconstructed/bridge-core/src/tool-input-validation.js';
import { resolveBridgeToolName } from '../reconstructed/bridge-core/src/bridge-tool-name.js';
import { Semaphore as CommunitySemaphore } from '../community/bridge-core/concurrency.mjs';

const generated=await reconstruct({write:false});
const original=await readFile(path.join(ROOT,generated.report.origin),'utf8');

test('reconstruction is deterministic; every original declaration hash and generated byte matches',async()=>{
  const stored=JSON.parse(await readFile(path.join(ROOT,'reconstructed/bridge-core/provenance.json'),'utf8'));
  assert.deepEqual(stored,generated.report);
  assert.deepEqual((await readdir(path.join(ROOT,'reconstructed/bridge-core/src'))).sort(),[...generated.files.keys()].sort());
  for(const m of generated.report.modules){
    const bytes=await readFile(path.join(ROOT,'reconstructed/bridge-core',m.file));assert.equal(hash(bytes),m.sha256);
    for(const d of m.declarations)assert.equal(hash(original.slice(d.start,d.end)),d.originalSha256);
  }
  assert.equal(generated.report.moduleCount,24);
  assert.ok(generated.report.sourceLabelIndex.some(m=>m.headingOffsets.length>1));
});

test('every reconstructed module loads in Node without npm runtime packages',async()=>{
  for(const m of generated.report.modules){
    const loaded=await import(pathToFileURL(path.join(ROOT,'reconstructed/bridge-core',m.file)));
    assert.deepEqual(Object.keys(loaded).sort(),m.exports);
  }
  assert.equal('dispatchFileTool' in fileTools,false);
});

test('scope analysis sees lexical dependencies, not property names or shadowed parameters',()=>{
  assert.deepEqual(scopeInfo('function f(local) { return external.call(local); }').free,['external']);
  assert.deepEqual(scopeInfo('const external = 1; function f() { return external; }').free,[]);
  assert.deepEqual(scopeInfo('const f = () => hidden;').free,['hidden']);
  assert.doesNotThrow(()=>assertOmittableInitializer(scopeInfo('init_define_SHUNCODE_BUILD_INFO();').ast.body[0],'fixture'));
  for(const code of ['state.ready = true;','startServer();','init_define_SHUNCODE_BUILD_INFO(extra);'])assert.throws(()=>assertOmittableInitializer(scopeInfo(code).ast.body[0],'fixture'),/Unmodeled top-level statement/);
});

test('tool catalogue contains 5 file tools and 8 IDE tools; wait stays excluded from Bridge',()=>{
  assert.equal(fileTools.FILE_TOOL_DEFINITIONS.length,5);assert.equal(IDE_TOOL_DEFINITIONS.length,8);
  assert.equal(new Set([...fileTools.FILE_TOOL_NAMES,...IDE_TOOL_NAMES]).size,13);
  assert.deepEqual([...BRIDGE_EXCLUDED_TOOL_NAMES],['wait']);
  for(const d of [...fileTools.FILE_TOOL_DEFINITIONS,...IDE_TOOL_DEFINITIONS])assert.equal(d.inputSchema.type,'object');
  assert.equal(resolveBridgeToolName('mcp__shuncode__read_files',fileTools.isFileToolName),'read_files');
});

test('legacy input normalization is non-mutating and refuses conflicting aliases',()=>{
  const input={path:'src/a.js',start:2,endLine:4};
  assert.deepEqual(compat.normalizeFileToolInput('read_file',input),{files:[{path:'src/a.js',start_line:2,end_line:4}]});
  assert.deepEqual(input,{path:'src/a.js',start:2,endLine:4});
  assert.throws(()=>compat.normalizeFileToolInput('search_files',{query:'one',pattern:'two'}),/conflicting/);
  assert.throws(()=>compat.normalizeFileToolInput('search_files',{paths:['a','b'],pattern:'x'}),/exactly one path/);
});

test('schema validation and tool parsers are separate checks, not a filesystem sandbox',()=>{
  const schema=fileTools.FILE_TOOL_DEFINITIONS.find(t=>t.name==='read_files').inputSchema;
  assert.throws(()=>validateToolInput('read_files',schema,{files:[]}),/INVALID_ARGUMENT/);
  assert.throws(()=>validateToolInput('read_files',schema,{files:[{path:'a'}],unexpected:true}),/INVALID_ARGUMENT/);
  assert.throws(()=>fileTools.parseReadFilesInput({files:[{path:'a',start_line:0}]}),/integer >= 1/);
  assert.equal(fileTools.parseSearchFilesInput({pattern:'needle'}).pattern,'needle');
  // A syntactically valid path is not proof it is within a workspace. That
  // enforcement lives in the not-yet-reconstructed file-operation layer.
  assert.equal(fileTools.parseReadFilesInput({files:[{path:'../outside'}]}).files[0].path,'../outside');
});

test('isolated original declarations and ESM reconstruction agree on deterministic parser cases',()=>{
  // Execute ONLY the hash-checked, reviewed declaration closure, never the full
  // extension bundle. VM is a comparison harness, not a security sandbox.
  const declarations=generated.report.modules.flatMap(m=>m.declarations).sort((a,b)=>a.start-b.start);
  const baselineSource=declarations.map(d=>d.snapshotMetadataAssignment?`const ${d.names[0]} = ${original.slice(d.start,d.end)};`:original.slice(d.start,d.end)).join('\n');
  const require=createRequire(import.meta.url);
  const baseline=vm.runInNewContext(baselineSource+'\n({normalizeFileToolInput,parseReadFilesInput,parseSearchFilesInput,validateToolInput,FILE_TOOL_DEFINITIONS})',{
    require:specifier=>{assert.equal(specifier,'node:crypto');return require(specifier);},Buffer,setTimeout,clearTimeout,
  },{timeout:1000});
  const canonical=fn=>{try{return JSON.stringify({result:fn()});}catch(e){return JSON.stringify({error:e.message});}};
  const cases=[{},null,{path:'a',start:2},{files:['a']},{files:[]},{files:[{path:'a',start_line:0}]},{query:'a',pattern:'b'}];
  for(const input of cases){
    for(const tool of ['read_files','search_files'])assert.equal(canonical(()=>compat.normalizeFileToolInput(tool,input)),canonical(()=>baseline.normalizeFileToolInput(tool,input)));
    for(const name of ['parseReadFilesInput','parseSearchFilesInput'])assert.equal(canonical(()=>fileTools[name](input)),canonical(()=>baseline[name](input)));
  }
  assert.equal(JSON.stringify(fileTools.FILE_TOOL_DEFINITIONS),JSON.stringify(baseline.FILE_TOOL_DEFINITIONS));
});

test('community candidate fixes shrinking admission without revoking in-flight work',async()=>{
  const s=new CommunitySemaphore(3),a=await s.acquire(),b=await s.acquire(),c=await s.acquire();
  let admitted=false;const waiting=s.acquire().then(release=>{admitted=true;return release;});
  s.setLimit(1);a();await Promise.resolve();assert.equal(admitted,false);assert.equal(s.active,2);
  b();await Promise.resolve();assert.equal(admitted,false);assert.equal(s.active,1);
  c();const release=await waiting;assert.equal(admitted,true);assert.equal(s.active,1);release();assert.equal(s.active,0);
});

test('community candidate retains queued cancellation and single-use releasers',async()=>{
  const s=new CommunitySemaphore(2),a=await s.acquire(),b=await s.acquire(),abort=new AbortController();
  const pending=s.acquire(abort.signal);s.setLimit(1);abort.abort();await assert.rejects(pending);
  a();a();assert.equal(s.active,1);b();assert.equal(s.active,0);assert.equal(s.waiting,0);
});

test('community candidate differs from the snapshot only in its documented admission guard',async()=>{
  const snapshot=await readFile(path.join(ROOT,'reconstructed/bridge-core/src/concurrency.js'),'utf8');
  const candidate=await readFile(path.join(ROOT,'community/bridge-core/concurrency.mjs'),'utf8');
  assert.equal(candidate.slice(candidate.indexOf('var Semaphore')),snapshot.slice(snapshot.indexOf('var Semaphore')).replace('const next = this.queue.shift();','const next = this.current < this.max ? this.queue.shift() : undefined;'));
});
