// Hand-written types for reconstructed/bridge-core/src/apply-patch.js
//
// PROVENANCE — WEAKER THAN THE EARLIER MODULES. Read this before trusting it.
//
// No recovered .ts file imports this module, so there is **no FIRST-HAND
// evidence**: not one type name here is known to be the author's own spelling.
// The names below are mine. The shapes are not guesses, but the names may not
// match what the author wrote.
//
//   STRUCTURAL  The input contract is exact. APPLY_PATCH_TOOL.inputSchema
//               (file-tool-registry.js:27) is a JSON Schema that survived
//               compilation as a runtime value, and parseApplyPatchInput
//               (line 533) enforces it: `patch` is a required non-empty
//               string, `expected_versions` an optional map of path to
//               `sha256:` string, no additional properties.
//   OBSERVED    The success result is the return literal at line 736, the file
//               entries at line 727, the config at line 13, and all fifteen
//               error codes are literal PatchToolError constructions.
//   INFERRED    applyPatch resolves only with a success result. normalizeError
//               (line 697) re-throws on every path - it never returns - so the
//               declared return type has no failure branch. Failures arrive as
//               a thrown PatchToolError.
//
// Anything not listed above is internal machinery; it is exported but is not
// part of a contract any caller depends on, so it is typed conservatively.

/** Every error code PatchToolError is constructed with. */
export type PatchErrorCode =
	| 'ABORTED'
	| 'BINARY_FILE'
	| 'FILE_ALREADY_EXISTS'
	| 'FILE_NOT_FOUND'
	| 'FILE_TOO_LARGE'
	| 'INVALID_PATCH'
	| 'IO_ERROR'
	| 'NOT_A_FILE'
	| 'PATCH_TOO_LARGE'
	| 'PATH_OUTSIDE_WORKSPACE'
	| 'PERMISSION_DENIED'
	| 'ROLLBACK_FAILED'
	| 'STALE_FILE'
	| 'TOO_MANY_FILES'
	| 'TOO_MANY_OPERATIONS'
	| 'UNSUPPORTED_ENCODING';

/**
 * What a patch does to one file.
 *
 * 'move' is a distinct action, not an update with a destination: the planner
 * emits it at line 505 and canonical-diff renders rename headers for it. An
 * earlier draft of this file omitted it.
 */
export type PatchAction = 'add' | 'update' | 'delete' | 'move';

/**
 * Thrown for every failure.
 *
 * The message is prefixed with the code, so `error.message` already carries it.
 */
export class PatchToolError extends Error {
	constructor(code: PatchErrorCode, message: string);
	readonly code: PatchErrorCode;
}

/** Limits applied to a single apply_patch call. */
export interface ApplyPatchConfig {
	maxPatchBytes: number;
	maxOperations: number;
	maxFiles: number;
	maxFileBytes: number;
	/** Diffs beyond this are truncated, not rejected. */
	maxDiffBytes: number;
}

export const DEFAULT_APPLY_PATCH_CONFIG: ApplyPatchConfig;

/**
 * Tool input. Mirrors APPLY_PATCH_TOOL.inputSchema exactly.
 */
export interface ApplyPatchInput {
	/** Codex-style text between `*** Begin Patch` and `*** End Patch`. */
	patch: string;
	/**
	 * Optional optimistic-concurrency check, keyed by file path.
	 *
	 * Values must be `sha256:...` strings as returned by read_files. A mismatch
	 * fails the whole patch with STALE_FILE rather than editing a file that
	 * changed after it was read.
	 */
	expected_versions?: Record<string, string>;
}

export interface ApplyPatchContext {
	workspaceRoots: readonly string[] | (() => readonly string[]);
	signal?: AbortSignal;
	/** Per-call overrides merged over DEFAULT_APPLY_PATCH_CONFIG. */
	config?: Partial<ApplyPatchConfig>;
}

/** One file touched by the patch. */
export interface ApplyPatchFileResult {
	action: PatchAction;
	path: string;
	/** Present only when the file moved. */
	destination_path?: string;
	/** `sha256:...` before the change; undefined for an add. */
	old_version?: string;
	/** `sha256:...` after the change; undefined for a delete. */
	new_version?: string;
	additions: number;
	deletions: number;
}

export interface ApplyPatchSummary {
	files_changed: number;
	additions: number;
	deletions: number;
}

/**
 * A successful application.
 *
 * `diff` is generated by the runtime from validated old/new contents - it is
 * not an echo of the supplied patch, which is why diff_source is recorded.
 * `multi_file_atomic` is false by design: writes are staged and rollback-
 * capable, but a multi-file commit is not one filesystem transaction.
 */
export interface ApplyPatchSuccess {
	status: 'success';
	files: ApplyPatchFileResult[];
	summary: ApplyPatchSummary;
	diff: string;
	diff_truncated: boolean;
	diff_format: 'unified';
	diff_source: 'runtime_old_vs_new';
	commit_strategy: 'staged_atomic_per_file';
	multi_file_atomic: false;
}

/**
 * Applies a multi-file patch.
 *
 * Preflights everything before mutating, takes per-file locks, then commits.
 * Nothing is applied partially: a failure anywhere rolls back.
 *
 * Resolves only on success - every failure path throws a PatchToolError, so
 * there is no error branch in the resolved value.
 *
 * @throws PatchToolError
 */
export function applyPatch(
	input: ApplyPatchInput,
	context: ApplyPatchContext
): Promise<ApplyPatchSuccess>;

/** Renders a result as the text block the model sees. */
export function formatApplyPatchForModel(result: ApplyPatchSuccess): string;

// --- Internal machinery -----------------------------------------------------
// Exported by the module but not part of any caller-facing contract. Typed at
// the boundary rather than given invented interfaces: naming their internal
// structures would imply knowledge of the author's vocabulary that does not
// survive in the shipped code.

/** Serialises writes to one path. */
export class Mutex {
	lock(): Promise<() => void>;
}

export const fileLocks: Map<string, Mutex>;
export function lockFor(path: string): Mutex;
export function withFileLocks<T>(
	paths: readonly string[],
	fn: () => Promise<T>
): Promise<T>;

/** Parses patch text into operations. @throws PatchToolError on bad syntax. */
export function parsePatch(patchText: string, config: ApplyPatchConfig): unknown[];

/** Validates the whole patch without mutating. @throws PatchToolError. */
export function preflight(
	operations: readonly unknown[],
	input: ApplyPatchInput,
	context: ApplyPatchContext,
	config: ApplyPatchConfig
): Promise<{ plans: unknown[]; lockPaths: string[] }>;

export function applyHunks(
	filePath: string,
	snapshot: unknown,
	hunks: readonly unknown[]
): { lines: string[]; additions: number; deletions: number };

/**
 * Locates a context sequence in a file.
 *
 * Returns -1 when absent, and the match must be unique - an ambiguous context
 * is rejected rather than resolved to the first hit.
 */
export function findSequence(
	lines: readonly string[],
	needle: readonly string[],
	requireEndOfFile: boolean
): number;

export function commitPlans(plans: readonly unknown[], signal?: AbortSignal): Promise<void>;
export function rollbackPlans(completed: readonly unknown[]): Promise<void>;
export function stagePlans(plans: readonly unknown[]): Promise<void>;

/** Always throws; normalises an unknown error into a PatchToolError. */
export function normalizeError(error: unknown): never;

export function hashBytes(bytes: Uint8Array): string;

/**
 * Re-encodes file lines, preserving the file's original style.
 *
 * Note the argument order and that it takes lines, not text: line ending and
 * BOM are carried through explicitly so an edit does not silently convert
 * CRLF to LF or strip a BOM.
 */
export function encodeText(
	lines: readonly string[],
	endsWithNewline: boolean,
	eol: string,
	bom: boolean
): Buffer;

export function pathExists(filePath: string): Promise<boolean>;

/** Note the order: root first, then the candidate target. */
export function isInsideRoot(root: string, target: string): boolean;

export function normalizePatchPath(value: string): string;

/** Async: it resolves symlinks. @throws PatchToolError PATH_OUTSIDE_WORKSPACE. */
export function canonicalRoots(roots: readonly string[]): Promise<string[]>;
export function truncateUtf8(text: string, maxBytes: number): { text: string; truncated: boolean };
